name: CI

on: 
  workflow_run:
    workflows: ["Run clang-format"]
    types:
      - completed

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cat ${GITHUB_WORKSPACE}/test.hpp
